name: job_application_bot
channels:
  - conda-forge
dependencies:
  - python=3.10
  - beautifulsoup4
  - requests
  - pandas
  - google-auth
  - google-auth-oauthlib
  - google-auth-httplib2
  - google-api-python-client
  - pip
  - pip:
    - selenium
    - webdriver-manager
    - chromedriver-autoinstaller
    - cryptography
    - geckodriver-autoinstaller
